export const CREATE_DEVICE = "CREATE_DEVICE";
export const LOAD_DEVICES_SUCCESS = "LOAD_DEVICES_SUCCESS";

export const LOAD_TYPES_SUCCESS = "LOAD_TYPE_SUCCESS";

export const UPDATE_DEVICE_SUCCESS = "UPDATE_DEVICE_SUCCESS";
export const CREATE_DEVICE_SUCCESS = "CREATE_DEVICE_SUCCESS";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

// no success
export const DELETE_COURSE_OPTIMISTIC = "DELETE_COURSE_OPTIMISTIC";
